apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoker-dpl
  labels:
    app: invoker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoker
  template:
    metadata:
      labels:
        app: invoker
    spec:
      containers:
      - name: invoker
        image: invoker
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: invoker-svc
spec:
  type: NodePort
  selector:
    app: invoker
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
