apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: python
    image: python:latest
    command: ['python', '-m', 'http.server', '8000']
    ports:
    - containerPort: 8000
